<Project>
  <ItemGroup Condition="'$(SHINYPDF_DEVCONTAINER)' == 'true' Or $([MSBuild]::IsOSPlatform('Linux'))">
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="4.153.1" PrivateAssets="all" />
    <PackageReference Include="HarfBuzzSharp.NativeAssets.Linux" Version="14.2.1.301" PrivateAssets="all" />
  </ItemGroup>
</Project>